# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a18fb7b864ab3b1ba348468706c1a03127ba55238bdfc03f9f02f8483aa95dce2afea4b6cdf69e25687c3ea2944c7f95bae8eab3acf1cf41bc6ca3d2ffe5c7
  user: radmin
  password: [Password1]

test:
  secret_key_base: abe4b74ff77940f14ebb3fd987c3f9a471a118588cea401d064bd9f73dbad40922403561cfa2c1ecc0834c30f34a5b3b2ba12c75aee94809e3272f5826f79b2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user: radmin
  password: [Password1]
